import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Deploy new project to Vercel Test 1</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          DONE: Deploy new project to <span className="text-[hsl(280,100%,70%)]">Vercel</span> Test 1
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8 text-white">
            <h2>
              step 2 - import stuff DONE. Imported dependencies and the app deploys fine.
            </h2>
            <h3>
              step 3 - modify directory structure (current task)
            </h3>
            <h4>
              step 4 - add functions
            </h4>
            <h5>
              step 5 - clean up code
            </h5>
            
          </div>
        </div>
      </main>
    </>
  );
}
